// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMEsdnAQTzyR9aObEiNxrQI5LaIMIglDE',
    appId: '1:1041879051237:web:c12513d31c2db4aeffdd0c',
    messagingSenderId: '1041879051237',
    projectId: 'authenflutter-9b820',
    authDomain: 'authenflutter-9b820.firebaseapp.com',
    storageBucket: 'authenflutter-9b820.appspot.com',
    measurementId: 'G-7PV02Q96S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzG9DS-KvGoMRplYmq18yqcOYgU7dz1dM',
    appId: '1:1041879051237:android:aad7b48a99a08b4affdd0c',
    messagingSenderId: '1041879051237',
    projectId: 'authenflutter-9b820',
    storageBucket: 'authenflutter-9b820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSo0YYhTKWX-pyNDjKOJMC64QWf-fMvL8',
    appId: '1:1041879051237:ios:40d2e160e98f5315ffdd0c',
    messagingSenderId: '1041879051237',
    projectId: 'authenflutter-9b820',
    storageBucket: 'authenflutter-9b820.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSo0YYhTKWX-pyNDjKOJMC64QWf-fMvL8',
    appId: '1:1041879051237:ios:4f860cf257a08fcaffdd0c',
    messagingSenderId: '1041879051237',
    projectId: 'authenflutter-9b820',
    storageBucket: 'authenflutter-9b820.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
